//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman_Aidat_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiListesi
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string TelefonNo { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public Nullable<int> OdenenTutar { get; set; }
        public string OdemeTarihi { get; set; }
    }
}
