//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman_Aidat_Takip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apartmanTakibiEntities : DbContext
    {
        public apartmanTakibiEntities()
            : base("name=apartmanTakibiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KisiListesi> KisiListesis { get; set; }
        public virtual DbSet<OdemeKisiListesi> OdemeKisiListesis { get; set; }
    }
}
